### ISSUE TITLE
[BUG]: hyperColor shakes the screen

### ISSUE THREAD

**Issue by brunocalado** [RPG-Made-Simple/FVTT-ChromaticCanvas#1]
### Discord Username

@mestredigital

### Browsers

Chrome

### What Happened?

hyperColor shakes the screen. I Just want it to change color

### Reproduction Steps

```bash
ChromaticCanvas.hyperColor({
  intesity: 1,
  duration: 100,
  iterations: 500,
});
```

**Comment by ZotyDev** [comment]
That is a somewhat indended feature, I just copied the `drugged` effect from Kandashi's fluid canvas.
This module, as a whole, was more of a test till now, the proof is that I actually just copied KFC and changed some parameters, but I'm currently refactoring many of the systems.
Now, this "fix" will be present on `v2.0.0` by default, alongside RPG-Made-Simple/FVTT-Code#4.
