### ISSUE TITLE
[FEATURE]: Gray Mode

### ISSUE THREAD

**Issue by brunocalado** [RPG-Made-Simple/FVTT-ChromaticCanvas#4]
### Discord Username

@mestredigital

### Enhancement Type

Feature

### Request

I like a gray mode or something like it to simulate something that happen a long time ago. Like in the movies or games. A gray mode or a blur on the edges mode.

**Comment by ZotyDev** [comment]
Thanks for the suggestion! I added a grayscale filter and a old movie filter. I'm currently adding more filters and implementing a custom effect manager, v2.0.0 will contain all the new features and changes.
